# Configuration for travis
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements/travis.txt

before_script:
  - flake8 src setup.py

script:
  - coverage run --source=src/ofxstatement setup.py test -v
  - python setup.py install

after_success:
  coveralls
